language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-selenium-plugin-1.0.0-beta.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-selenium-plugin
  api_key:
    secure:
      secure: UvrPGHGuPKrwBaDq5UebjcCeZciFiRR2qnKb40IXtNwb8YBPDevjDjar1iNpd1dEsSVvstwzz78uPSx4gB88Lsa1B0zI54DdwN+cqh2YGSWe2mc8aevmK35RJkWNsV5ilmmDormZsld91WfDguVGCvv0IiOXro62+hlC1MwoV+y/XiRw2Xq5t8tnH0THlIoHEsExYEpjAiB3WZQX/EnCxI72wFGXNDOsV+3nVffdOaBsficRdmXx/SpOOKCvJqyx8icWiv1ZNhE0Cxwc8+wGrvpdC/uQXjfwQOJn2NTsvLail0X1L0F6o8IqstWAfweJZoDhBWuS0uCYT+vkt4jMf4b2O20KkZrw1bxE0H0vLIuJq0gmDzAS45teu96EY2hl4C/jWy/uV0CpQKeXpWA94ce5qvR/IHQRFVm7V15rfx+KulSpjHsomcKLZ9DHquvuIc2I9ML/eF2ZDyi1g/hu2QirQbf9/NhH/E3v7PtEzPHa122ApYZbTHRGYLrqWqaEBUvBd3bsE9FpktVf2aslCbkT/UdsePOn9v8K7SGd6gB6YKs84BxEpiXdHp+auaQlrakEEXjTQXRw+8XSbaTVK0cE6eUjyYgGeXVZcYs+XvWAR0iJz2peg34dWKPLFri2e+EMXTBalR62YKwuJkOQ2tCleFYmxvvrbKX37ihf1zw=
notifications:
  hipchat:
    rooms:
      secure: J9EY6bKsCPo2o5sRnMgc7EikObAGIeRm/2OX/0/NfJc42wywQXN74Gkfa0/lFZERKcPFv3Xy2uhVO2ityk9wYjeqq+VKgaKLfi5XLo4pkbcT8cAY1zKF9WWSABANUGSqAhFl0dbth+CSJOTIe/nIFW6E8yZ85/LThFeKKkuWj6rlvtVHS2xAjQR8Kxi/Lz0jObksfc9rmm0/EdJn5ZUx/6oN02YEf6MyHPRG//RzXgNUyQrVKrhBwq8yOz1gz6yEoi7RpUyhyeiY0Wyn8+1VWnj8b/8UjQXy+TBga2MgqHOGofSo7el1pbRhy+URvDZzIovL+KsNrmHMsaqbwfuDeiHb0+wehb29rxm2cOg/AlCeNllM8Skb3W3sj0MkGYviITObxuz9/ghnM/nrnCWkmkvEdo5hHiysM82SaQ5cEnZEGDpaGlLMU6rQ7N5Ay3jqCk+RJydTYqg+ofvbWdNnM2zL0cdZf/8N8TGtHo2kN111TeHjnn3ulGGR2XwvU4IUiUvhHITXPWBLcCagfd6XdQK6aJPTArll6Fo7n//GHpY+lNdkxdd1SnQRZL7sOzqHKPHX3br4ASP/pcSIJZksexTqVnieSNvZm6d0l20IQnS/6CJrauXXorHuDzwLKFiVvvx+/SSRY66o5O9OrPGH5OGkovPoC1xqTwDCtV6gP1o=
